"""Notification model — stores in-app notifications generated by system events."""

from sqlalchemy import Column, Integer, String, Text, Boolean, DateTime, Float
from sqlalchemy.sql import func

from app.database import Base


class Notification(Base):
    """In-app notification record."""
    __tablename__ = "notifications"

    id = Column(Integer, primary_key=True, autoincrement=True)
    type = Column(String(20), nullable=False, default="system")   # price_alert, success, warning, system
    title = Column(String(200), nullable=False)
    message = Column(Text, nullable=False)
    read = Column(Boolean, default=False)
    route = Column(String(10), nullable=True)
    price_change = Column(Float, nullable=True)
    created_at = Column(DateTime, server_default=func.now())
